
def bubble_sort(list_to_sort):                              # O(n^2)
    for i in range(len(list_to_sort)):                      # O(n)
        swapped = False                                     # O(n)
        for index in range(0, len(list_to_sort) - 1 - i):   # O(n^2)
            current_element = list_to_sort[index]           # O(n^2)
            next_element = list_to_sort[index + 1]          # O(n^2)
            if current_element > next_element:              # O(n^2)
                list_to_sort[index] = next_element          # O(n^2)
                list_to_sort[index + 1] = current_element   # O(n^2)
                swapped = True                              # O(n^2)
        print(f"Iteración {i}: {list_to_sort}")             # O(n^2)
        if not swapped:                                     # O(n)
            break                                           # O(n)
    print(list_to_sort)                                     # O(n)

def print_numbers_times_2(numbers_list):                    # O(n)
    for number in numbers_list:                             # O(n)
        print(number * 2)                                   # O(n)
		
def check_if_lists_have_an_equal(list_a, list_b):           # O(n^2)
    for element_a in list_a:                                # O(n)
        for element_b in list_b:                            # O(n^2)
            if element_a == element_b:                      # O(n^2)
                return True                                 # O(1)
    return False                                            # O(1)

def print_10_or_less_elements(list_to_print):               # O(1)
    list_len = len(list_to_print)                           # O(1)
    for index in range(min(list_len, 10)):                  # O(1)
        print(list_to_print[index])                         # O(1)
		
def generate_list_trios(list_a, list_b, list_c):            # O(n^3)
    result_list = []                                        # O(1)
    for element_a in list_a:                                # O(n)
        for element_b in list_b:                            # O(n^2)
            for element_c in list_c:                        # O(n^3)
                result_list.append(f'{element_a} {element_b} {element_c}')  # O(n^3)
    return result_list                                      # O(n^3)